---
# tasks file for pip

# python-dev is usually needed with pip to build the wheels
- name: Install pip
  package:
    name:
      - python-pip
      - python-dev
      - python3-pip
      - python3-dev
  when:
    - ansible_os_family == "Debian"

- name: Install pip
  package:
    name:
      - python27-pip
      - python27-devel
      - python36-pip
      - python36-devel
  when: ansible_os_family == "RedHat"
