---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install pip3
  block:
    - name: Install pip3 via package manager
      ansible.builtin.package:
        name: "{{ python3_package_names }}"

    # For Debian Buster, upgrade pip3 via python in order to get a version new
    # enough to support pyproject.toml, which is required for installing some
    # packages.  The latest version of pip3 available via the package manager is
    # too old to support pyproject.toml.
    - name: Upgrade pip3 via python for Debian Buster
      ansible.builtin.pip:
        name: pip
        # ansible-lint generates a warning that "package installs should
        # not use latest" here, but we truly do want to use it here.
        state: latest  # noqa package-latest
        executable: pip3
      when: >-
        ansible_distribution == 'Debian' and
        ansible_distribution_release == 'buster'

- name: Install pip2
  ansible.builtin.package:
    name: "{{ python2_package_names }}"
  when: pip_install_pip2
