---
# tasks file for pip

# python-dev is usually needed with pip to build the wheels associated
# with python packages
- name: Install pip (Debian)
  package:
    name:
      - python-pip
      - python-dev
      - python3-pip
      - python3-dev
  when:
    - ansible_os_family == "Debian"

- name: Install pip (AmazonLinux)
  package:
    name:
      - python27-pip
      - python27-devel
      - python36-pip
      - python36-devel
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"

- name: Install pip (Fedora)
  package:
    name:
      - python2-pip
      - python2-devel
      - python3-pip
      - python3-devel
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"
